---
title: "Tests of Independence"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{independence}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(discretefit)

plot_speed <- function(x, reps)  {
  
  speed <- bench::mark(min_iterations = 100, 
                       check = FALSE,
                      stats = chisq.test(x, simulate.p.value = TRUE, B = reps),
                      discretefit = chisq_ind(x, reps = reps)
                       )

  ggplot2::autoplot(speed) +
    ggplot2::theme_minimal() +
    ggplot2::xlab(NULL) +
    ggplot2::ylab(NULL) 

}
```

```{r}
ind_sim2_r <- function(x, reps)  {

  n <- sum(x)
  nr <- as.integer(nrow(x))
  nc <- as.integer(ncol(x))
  sr <- rowSums(x)
  sc <- colSums(x)
  E <- outer(sr, sc, "*") / n

  STATISTIC <- sum((x - E)^2 / E)

  ind_sim2(reps = reps,
          r_sums = sc,
          c_sums = sr,
          as.numeric(E),
          seed = sample.int(.Machine$integer.max, 1),
          statistic = STATISTIC,
          tolerance = 0)
}

```

```{r}
x <- matrix(data = 1:16, ncol = 4)

ind_sim2_r(x, reps = 10000)
chisq.test(x, simulate.p.value = TRUE)$p.value

```




```{r}
x <- matrix(data = 1:16, ncol = 4)

plot_speed(x, reps = 10000)

```

```{r}
x <- c(17066, 48, 
       14464, 38,
       788, 5,
       126, 1,
       37, 1)


x <- matrix(x, ncol = 5)

plot_speed(x, reps = 1000)

speed <- bench::mark(min_iterations = 100, 
                       check = FALSE,
                      discretefit = chisq_ind(x, reps = 1000),
                      discretefit2 = chisq_ind(x, reps = 1000)
                       )

  ggplot2::autoplot(speed) +
    ggplot2::theme_minimal() +
    ggplot2::xlab(NULL) +
    ggplot2::ylab(NULL) 


```

```{r}
x <- c(48, 17066, 
        38, 14464,
       5,  788,
        1, 126,
        1, 37)


x <- matrix(x, ncol = 2, byrow = TRUE)

plot_speed(x, reps = 1000)

```
