---
title: "Random Contingecy Tables with Fixed Margins"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{random_contingecy_tables_with_fixed_margins}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(discretefit)
```

The following comparisons between RCONT (Boyett, 1979) and RCONT2 (Patefield, 1981) are taken given by Patefield (1981).

2 x 7, n = 100
```{r}

rsums <- c(50, 50)
csums <- c(rep(14, 5), 15, 15)

bench::mark(min_iterations = 10,

  x <- r2dtable(1000, rsums, csums)
  
)

bench::mark(min_iterations = 20,
  
  y <- RCONT(1000, rsums, csums)
  
)

```

2 x 7, n = 1000

```{r}

rsums <- c(500, 500)
csums <- c(rep(140, 5), 150, 150)

speed <- bench::mark(min_iterations = 100, check = FALSE, 
 rcont2 = r2dtable(10000, rsums, csums),
 rcont = RCONT(10000, rsums, csums),
 rcont_cpp = RCONT_cpp(10000, rsums, csums)
)

ggplot2::autoplot(speed) +
  ggplot2::theme_minimal() +
  ggplot2::xlab(NULL) +
  ggplot2::ylab(NULL) +
  ggplot2::ggtitle("2 x 7, n = 1000")

```

6 x 6, n = 100

```{r}

rsums <- c(17, 17, 17, 17, 16, 16)
csums <- c(17, 17, 17, 17, 16, 16)

speed <- bench::mark(min_iterations = 20, check = FALSE, 
 rcont2 = r2dtable(10000, rsums, csums),
 rcont = RCONT(10000, rsums, csums),
 rcont_cpp = RCONT_cpp(10000, rsums, csums)
)

ggplot2::autoplot(speed) +
  ggplot2::theme_minimal() +
  ggplot2::xlab(NULL) +
  ggplot2::ylab(NULL) +
  ggplot2::ggtitle("6 x 6, n = 100")

```

6 x 6, n = 1000

```{r}

rsums <- c(170, 170, 170, 170, 160, 160)
csums <- c(170, 170, 170, 170, 160, 160)

speed <- bench::mark(min_iterations = 20, check = FALSE, 
 rcont_cpp = RCONT_cpp(1000, rsums, csums),
 rcont2 = r2dtable(1000, rsums, csums),
 rcont = RCONT(1000, rsums, csums)
)

ggplot2::autoplot(speed) +
  ggplot2::theme_minimal() +
  ggplot2::xlab(NULL) +
  ggplot2::ylab(NULL) +
  ggplot2::ggtitle("6 x 6, n = 1000")

```

6 x 6, n = 10000

```{r}

rsums <- c(1700, 1700, 1700, 1700, 1600, 1600)
csums <- c(1700, 1700, 1700, 1700, 1600, 1600)

bench::mark(min_iterations = 10,

  x <- r2dtable(1000, rsums, csums)
  
)

bench::mark(min_iterations = 20,
  
  y <- RCONT(1000, rsums, csums)
  
)

```

Seems that only when the average expected observations per cell is much greater than 100 (here 277) is RCONT2 faster. 

