// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// chisq_gof_cpp
double chisq_gof_cpp(IntegerVector vector_1, IntegerVector vector_2, double reps);
RcppExport SEXP _discretefit_chisq_gof_cpp(SEXP vector_1SEXP, SEXP vector_2SEXP, SEXP repsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type vector_1(vector_1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vector_2(vector_2SEXP);
    Rcpp::traits::input_parameter< double >::type reps(repsSEXP);
    rcpp_result_gen = Rcpp::wrap(chisq_gof_cpp(vector_1, vector_2, reps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_discretefit_chisq_gof_cpp", (DL_FUNC) &_discretefit_chisq_gof_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_discretefit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
