# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chisq_gof_cpp <- function(vector_1, vector_2, reps) {
    .Call('_discretefit_chisq_gof_cpp', PACKAGE = 'discretefit', vector_1, vector_2, reps)
}

