# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_p <- function(type, vector_1, vec_2_frac, reps, tolerance) {
    .Call('_discretefit_simulate_p', PACKAGE = 'discretefit', type, vector_1, vec_2_frac, reps, tolerance)
}

chisq_stat <- function(draws, vec_1_frac, vec_2_frac) {
    .Call('_discretefit_chisq_stat', PACKAGE = 'discretefit', draws, vec_1_frac, vec_2_frac)
}

RCONT_setup <- function(c_sums) {
    .Call('_discretefit_RCONT_setup', PACKAGE = 'discretefit', c_sums)
}

RCONT_tab <- function(x, bins, a, b) {
    .Call('_discretefit_RCONT_tab', PACKAGE = 'discretefit', x, bins, a, b)
}

RCONT_simulate <- function(v, r_sum, c_sum) {
    .Call('_discretefit_RCONT_simulate', PACKAGE = 'discretefit', v, r_sum, c_sum)
}

RCONT <- function(n, r_sum, c_sum) {
    .Call('_discretefit_RCONT', PACKAGE = 'discretefit', n, r_sum, c_sum)
}

cpp_shuffle <- function() {
    .Call('_discretefit_cpp_shuffle', PACKAGE = 'discretefit')
}

RCONT_setup_cpp <- function(c_sums) {
    .Call('_discretefit_RCONT_setup_cpp', PACKAGE = 'discretefit', c_sums)
}

RCONT_tab_cpp <- function(v, nbins, a, b) {
    .Call('_discretefit_RCONT_tab_cpp', PACKAGE = 'discretefit', v, nbins, a, b)
}

RCONT_simulate_cpp <- function(v, r_sum, c_sum) {
    .Call('_discretefit_RCONT_simulate_cpp', PACKAGE = 'discretefit', v, r_sum, c_sum)
}

RCONT_cpp <- function(n, r_sum, c_sum) {
    .Call('_discretefit_RCONT_cpp', PACKAGE = 'discretefit', n, r_sum, c_sum)
}

RCONT_cpp2 <- function(n, r_sums, c_sums) {
    .Call('_discretefit_RCONT_cpp2', PACKAGE = 'discretefit', n, r_sums, c_sums)
}

